### ISSUE TITLE
Error in production build

### ISSUE THREAD

**Issue by slavikdenis** [sindresorhus/normalize-url#51] opened 2017-12-13 08:41 UTC
Hello!

In the new version 2.0.0 there occurs an error while production build.

Error:
`ERROR in bundle-24382f917c9c63d5d406.js from UglifyJs
Unexpected token: operator (>) [./node_modules/normalize-url/index.js:29,0][bundle-24382f917c9c63d5d406.js:117649,29]`

Using:
"webpack": "^3.10.0"

Any ideas how should I fix this, instead of downgrading?

Thanks

**Comment by sindresorhus** [comment] 2017-12-13 11:18
Duplicate of #50

**Closed by sindresorhus** 2017-12-13 11:18 UTC
